# Postgres docker-compose from https://github.com/felipewom/docker-compose-postgres

services:
  database:
    image: 'postgres:latest'
    ports:
      - 127.0.0.1:15432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ./data/db-data/:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 127.0.0.1:15433:80
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - ./data/pgadmin-data/:/var/lib/pgadmin/

networks:
  postgres-network:
    driver: bridge
